site_name: TDMSchopper Documentation
site_description: "TDMSchopper: Collection of code that chops in time NTCAP data in order to perform mass-and lifetime measurements of ringed ions in a frequency broadband."
site_url: "https://DFreireF.github.io/TDMSchopper"
repo_url: "https://github.com/DFreireF/TDMSchopper"
edit_uri: "blob/main/docs/"
repo_name: "DFreireF/TDMSchopper"
site_dir: "site"
watch: [README.md]

theme:
  name: material
  highlightjs: true
  features:
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist

plugins:
  - search
  - mkdocstrings

nav:
  - Main page: index.md
  - Code Reference:
    - model: model.md
      
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/DFreireF
copyright: |
  &copy; 2023 <a href="https://github.com/DFreireF"  target="_blank" rel="noopener">David Freire Fernández</a>